### ISSUE TITLE
[FIX] Excessive Padding in Hero Section

### ISSUE THREAD

**Issue by HpatricioH** [HpatricioH/SlugLink#2]
## Problem Description

The padding bottom and top for the main hero section is too much, causing the main section to be too big and making the page scroll.

## Solution

Refer to the [document component](https://github.com/HpatricioH/SlugLink/blob/main/src/app/page.tsx) to implement the necessary changes. Specifically, focus on line 10 to adjust the padding, remove excess bottom padding, and reduce the top margin of the section.

## Visual Reference

Attached is an image highlighting the problem. This will provide a visual understanding of the issue that needs to be addressed.

![SlugLink Issue](https://github.com/HpatricioH/SlugLink/assets/59483053/5f03a205-db6d-4f46-bbc4-3faa3102de23)

Feel free to reach out if you have any questions or need further assistance.

**Comment by AKHIL-DyC** [comment]
I am new to open source ,I am finding it  difficult to set up the environment variables, although the issue is related to frontend is there any way where I can work around without these env set ups

**Comment by HpatricioH** [comment]
Hello @AKHIL-DyC, thank you for your interest in this issue. I've updated the[ .env.example](https://github.com/HpatricioH/SlugLink/blob/main/.env.example) file with the missing variables and instructions for setting up NEXTAUTH_SECRET and GITHUB variables. If you want to set up the GITHUB Authentication please follow this [guide](https://github.com/HpatricioH/SlugLink/blob/main/GITHUB_SETUP.md). For local development, you can use any alphanumeric characters for these variables. If you're new to open source, please read our [Contributing guide](https://github.com/HpatricioH/SlugLink/blob/main/CONTRIBUTING.md) to understand the process.

If you're working on this issue, let me know so I can assign it to you. Please use Tailwind and adhere to the existing project structure.

**Comment by AKHIL-DyC** [comment]
![slugf](https://github.com/HpatricioH/SlugLink/assets/119416316/c4f4fd8a-ecf2-49f5-97ff-3745d2aa2f4b)
any suggestions

**Comment by AKHIL-DyC** [comment]
@HpatricioH

**Comment by HpatricioH** [comment]
@AKHIL-DyC  Thank you for your contribution. Please open a PR so I can review the changes and provide feedback if needed.

**Comment by AKHIL-DyC** [comment]
@HpatricioH  sorry for late response ,have raised a pr #4
